# Generated by Django 5.0.6 on 2025-03-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='types_activities',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.activity', verbose_name='Рекомендованные виды деятельности'),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_recommendations',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.personalityrecommendation', verbose_name='Персональные рекомендации'),
        ),
    ]
