# Generated by Django 5.0.6 on 2025-04-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personalityrecommendation_user_types_activities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalityrecommendation',
            options={'verbose_name': 'Персональные рекомендации', 'verbose_name_plural': 'Персональные рекомендации'},
        ),
    ]
