# Generated by Django 5.0.6 on 2025-03-20 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_statuses(apps, schema_editor):
    Status = apps.get_model("tests", "Status")
    statuses = ["завершен", "в процессе", "не завершен"]
    for status_name in statuses:
        Status.objects.get_or_create(name=status_name)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assigningtest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначен'),
        ),
        migrations.AddField(
            model_name='assigningtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.questiontype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='result',
            name='personality_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personality', verbose_name='Тип личности для результата'),
        ),
        migrations.AddField(
            model_name='result',
            name='tendencies',
            field=models.ManyToManyField(blank=True, related_name='results', to='users.tendency', verbose_name='Склонности для результата'),
        ),
        migrations.AddField(
            model_name='result',
            name='types_activities',
            field=models.ManyToManyField(blank=True, related_name='results', to='users.activity', verbose_name='Рекомендованные виды деятельности'),
        ),
        migrations.AddField(
            model_name='assigningtest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.status', verbose_name='Статус'),
        ),
        migrations.RunPython(add_statuses),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='assigningtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.result', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос'),
        ),
    ]
