# Generated by Django 5.0.6 on 2025-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_result_personality_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='trial',
            field=models.BooleanField(default=False, verbose_name='Пробное тестирование'),
        ),
    ]
