# Generated by Django 5.0.6 on 2025-04-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
